#include "../include/avm_structs.h"
#include "../include/avm_dispatcher.h"
#include "../include/binary_reader.h"
#include "../include/avm_trace.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void print_usage(const char* program_name) {
    printf("Usage: %s [--trace] [--dump] <binary_file.abc>\n", program_name);
    printf("  binary_file.abc - Alpha Binary Code file generated by compiler\n");
    printf("  --trace, -t     - print each instruction as it executes\n");
    printf("  --dump,  -d     - also dump the execution stack each step (implies --trace)\n");
}

int main(int argc, char** argv) {
    DEBUG_PRINT("=== Alpha Language Virtual Machine ===\n");

    // Parse flags and the single positional <binary_file> argument.
    const char* binary_filename = NULL;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--trace") == 0 || strcmp(argv[i], "-t") == 0) {
            vmTraceInstr = 1;
        } else if (strcmp(argv[i], "--dump") == 0 || strcmp(argv[i], "-d") == 0) {
            vmTraceInstr = 1;
            vmTraceStack = 1;
        } else if (argv[i][0] == '-') {
            fprintf(stderr, "Error: unknown flag '%s'\n", argv[i]);
            print_usage(argv[0]);
            return EXIT_FAILURE;
        } else if (binary_filename == NULL) {
            binary_filename = argv[i];
        } else {
            fprintf(stderr, "Error: too many arguments\n");
            print_usage(argv[0]);
            return EXIT_FAILURE;
        }
    }

    if (binary_filename == NULL) {
        fprintf(stderr, "Error: no binary file given\n");
        print_usage(argv[0]);
        return EXIT_FAILURE;
    }
    
    if (binaryReader_Load(binary_filename) != 0) {
        fprintf(stderr, "Error: Failed to load binary file '%s'\n", binary_filename);
        return EXIT_FAILURE;
    }

    // binaryReader_PrintInfo();
    
    // ----------------------------------------------------------------------------------
    
    InitializeStack();
    ax = safeCalloc(1, sizeof(struct VMMemCell), "allocating VM register ax");
    bx = safeCalloc(1, sizeof(struct VMMemCell), "allocating VM register bx");
    cx = safeCalloc(1, sizeof(struct VMMemCell), "allocating VM register cx");
    retval = safeCalloc(1, sizeof(struct VMMemCell), "allocating VM retval register");
    VM_PC = 1;
    skipNextTableGetElem = 0;

    while(!executionFinished) {
        VMInstruction_ExecuteCycle();
    }

    // ----------------------------------------------------------------------------------

    VMProgram_Cleanup();
    
    return EXIT_SUCCESS;
}